openapi: 3.0.0
info:
  title: Claime Verifier
  version: '1.0'
servers:
  - url: 'https://verifier.claime.io'
paths:
  '/{eoa}':
    parameters:
      - schema:
          type: string
        name: eoa
        in: path
        required: true
        description: EOA to verify.
    get:
      responses:
        '200':
          description: verification results.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    propertyType:
                      type: string
                    propertyId:
                      type: string
                    evidence:
                      type: string
                    method:
                      type: string
                    verified:
                      type: boolean
                    actual:
                      type: string
                    at:
                      type: string
                  required:
                    - propertyType
                    - propertyId
                    - evidence
                    - method
                    - verified
                    - actual
                    - at
        '404':
          description: EOA Not Found
