openapi: 3.0.0
info:
  title: Claime Verifier for Discord App
  version: '1.0'
servers:
  - url: 'https://discord.claime.io'
paths:
  /verify:
    post:
      operationId: post-discord-verify
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              x-examples:
                example-1:
                  discord:
                    userId: '0000'
                    guildId: '0000'
                    validity: 1
                    timestamp: 1
                    signature: '0000'
                  eoa:
                    signature: '0x0000'
                    message: '0x0000'
                    rawTx: '0x0000'
              properties:
                discord:
                  type: object
                  required:
                    - userId
                    - guildId
                    - validity
                    - timestamp
                    - signature
                  properties:
                    userId:
                      type: string
                      minLength: 1
                    guildId:
                      type: string
                      minLength: 1
                    validity:
                      type: number
                    timestamp:
                      type: number
                    signature:
                      type: string
                      minLength: 1
                eoa:
                  type: object
                  required:
                    - signature
                  description: either "message" or "rawTx" is required.
                  properties:
                    signature:
                      type: string
                      minLength: 1
                    message:
                      type: string
                      minLength: 1
                    rawTx:
                      type: string
                      minLength: 1
              required:
                - discord
                - eoa
            examples: {}
    parameters: []
  /:
    post:
      operationId: post-discord-app
      description: Endpoint for Discord App
      responses:
        '200':
          description: OK
    parameters: []
